app/controllers/courses_controller.rb
app/policies/course_policy.rb
app/views/courses/index.html.erb
app/views/courses/show.html.erb
app/views/layouts/application.html.erb
app/views/lessons/index.html.erb
app/views/lessons/show.html.erb

This PR fixes a bug in the course_policy and put notices in the application layout to reduce code.

notices moved to application layout, bug in course_policy fixed

---

app/views/courses/edit.html.erb
app/views/courses/new.html.erb
app/views/courses/show.html.erb
app/views/layouts/_navigation.html.erb
app/views/lessons/edit.html.erb
app/views/lessons/index.html.erb
app/views/lessons/new.html.erb
app/views/lessons/show.html.erb

@CharlesVincentAnderson please can you check this branch and give me your feedback, please. In this branch, I fixed the views that were overlapping.

Fix the views for courses and lessons

---

app/assets/stylesheets/documents.scss
app/controllers/documents_controller.rb
app/controllers/lessons_controller.rb
app/helpers/documents_helper.rb
app/models/course.rb
app/models/document.rb
app/models/lesson.rb
app/policies/document_policy.rb
app/policies/lesson_policy.rb
app/views/courses/edit.html.erb
app/views/courses/new.html.erb
app/views/courses/show.html.erb
app/views/documents/_form.html.erb
app/views/documents/edit.html.erb
app/views/documents/index.html.erb
app/views/documents/new.html.erb
app/views/documents/show.html.erb
app/views/layouts/_navigation.html.erb
app/views/lessons/edit.html.erb
app/views/lessons/index.html.erb
app/views/lessons/new.html.erb
app/views/lessons/show.html.erb
config/routes.rb
db/migrate/20210505070219_create_documents.rb
db/migrate/20210505145421_add_lesson_ref_to_documents.rb
db/migrate/20210505145837_add_course_ref_to_documents.rb
db/schema.rb
spec/helpers/documents_helper_spec.rb
spec/models/document_spec.rb
spec/requests/documents_spec.rb

@CharlesVincentAnderson Please could you check this branch and give me your feedback. I still need to work on the active storage (documents). We have another PR from yesterday, but that one is comparing with the main instead of development. the other pull request in the branch called documents.

Documents2part

---

app/controllers/lessons_controller.rb
app/models/course.rb
app/models/lesson.rb
app/views/courses/show.html.erb
app/views/layouts/_navigation.html.erb
app/views/lessons/edit.html.erb
app/views/lessons/index.html.erb
app/views/lessons/new.html.erb
app/views/lessons/show.html.erb
config/routes.rb

This PR nests the routes for lessons inside courses

lessons are now nested in courses

---

Gemfile
Gemfile.lock
app/controllers/documents_controller.rb
app/policies/document_policy.rb
app/views/courses/show.html.erb
app/views/documents/_form.html.erb
app/views/documents/course_index.html.erb
app/views/documents/edit.html.erb
app/views/documents/index.html.erb
app/views/documents/lesson_index.html.erb
app/views/documents/new.html.erb
app/views/documents/show.html.erb
app/views/layouts/_navigation.html.erb
app/views/lessons/show.html.erb
config/routes.rb

@CharlesVincentAnderson please check this branch and give me your feedback here is what we were working in the morning

Nested documents

---

app/assets/stylesheets/application.css
app/assets/stylesheets/courses.scss
app/assets/stylesheets/documents.scss
app/assets/stylesheets/lessons.scss
app/assets/stylesheets/pages.scss
app/controllers/documents_controller.rb
app/models/course.rb
app/models/lesson.rb
app/policies/course_policy.rb
app/views/courses/_form.html.erb
app/views/documents/_form.html.erb
app/views/lessons/_form.html.erb

This pr added 2 validations and required fields to the forms.

Trying validations

---

Gemfile
Gemfile.lock

This PR adds rack-cors to the gemfile

added rack-cors to gemfile

---

app/controllers/lessons_controller.rb
app/models/tagginglesson.rb
app/models/tags_course.rb

This PR cleans up some unneeded files

cleaned up unneeded files

---

app/models/course.rb
app/models/lesson.rb
app/views/lessons/show.html.erb
spec/factories/courses.rb
spec/factories/lessons.rb
spec/factories/tagginglessons.rb
spec/factories/tags_courses.rb
spec/models/course_spec.rb
spec/models/lesson_spec.rb

@CharlesVincentAnderson please could you check this PR I fixed a bug with tags for lessons that were pointing to courses.
You can approve and I can work in another branch.

Lesson spec

---

app/controllers/courses_controller.rb
app/controllers/tags_controller.rb
app/models/concerns/tag_list.rb
app/models/course.rb
app/models/lesson.rb
app/models/tag.rb
app/models/user.rb
app/views/courses/_form.html.erb

This PR allows users to update and remove tags for a course through the course update.

More tags crud

---

app/controllers/documents_controller.rb
app/controllers/lessons_controller.rb
app/javascript/packs/lessons.js
app/policies/lesson_policy.rb
app/views/courses/_form.html.erb
app/views/courses/index.html.erb
app/views/courses/show.html.erb
app/views/documents/index.html.erb
app/views/documents/show.html.erb
app/views/lessons/_form.html.erb
app/views/lessons/show.html.erb
spec/requests/courses_spec.rb

@CharlesVincentAnderson Chuck I finished the request rspec for courses with the basic test for course controller and where we render. Please can you check it and give me your feedback.

Complete rspec for request course

---

Gemfile
Gemfile.lock
spec/factories/courses.rb
spec/factories/users.rb
spec/policies/application_policy_spec.rb
spec/policies/course_policy_spec.rb
spec/requests/courses_spec.rb
spec/support/matchers/pundit_matcher.rb

@CharlesVincentAnderson please can you check this spec for policies.

Rspec policy

---

Gemfile
Gemfile.lock
spec/factories/courses.rb
spec/factories/users.rb
spec/policies/application_policy_spec.rb
spec/policies/course_policy_spec.rb
spec/policies/lesson_policy_spec.rb
spec/requests/courses_spec.rb
spec/support/matchers/pundit_matcher.rb

@CharlesVincentAnderson please could you check this policy spec for lessons and give me your feedback

Rspec policy3

---

Gemfile
Gemfile.lock
spec/factories/courses.rb
spec/factories/users.rb
spec/policies/application_policy_spec.rb
spec/policies/course_policy_spec.rb
spec/policies/lesson_policy_spec.rb
spec/requests/courses_spec.rb
spec/requests/lessons_spec.rb
spec/support/matchers/pundit_matcher.rb

@CharlesVincentAnderson more rspecs for lessons please do you mind to check it and give me your feedback

Rspec policy4

---

Gemfile
Gemfile.lock
README.md
app/controllers/courses_controller.rb
app/controllers/pages_controller.rb
app/models/concerns/course_search.rb
app/models/course.rb
app/views/courses/_form.html.erb
app/views/courses/edit.html.erb
app/views/courses/new.html.erb
app/views/pages/search.html.erb

This PR implements ElasticSearch and Searchkick to search courses.

Elasticsearch

---

app/controllers/courses_controller.rb
app/views/courses/_form.html.erb
app/views/courses/edit.html.erb

@CharlesVincentAnderson these are the changes to make it work Elastic Search.

Few changes to make it work the elastic search

---

app/controllers/pages_controller.rb
app/models/concerns/course_search.rb
app/views/courses/show.html.erb

This PR removed a byebug and added :commit to permitted params

removed byebug and added search_param

---

app/controllers/documents_controller.rb
app/controllers/pages_controller.rb

removed byebugs

---

app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/models/course.rb
app/models/search_item.rb
config/webpacker.yml
spec/requests/courses_spec.rb
spec/requests/lessons_spec.rb

This PR fixes a bug in the lesson update and fixes 2 tests

Lesson bug

---

app/controllers/lessons_controller.rb
app/models/concerns/lesson_search.rb
app/models/course.rb
app/models/lesson.rb
app/models/search_item.rb

@CharlesVincentAnderson please check this I was trying to help with the Elastic Search for lessons and fix the rspec errors.

Add lesson parameters to ES and fixing errors in the rspec

---

app/controllers/courses_controller.rb
app/models/course.rb
app/models/favorite_course.rb

@CharlesVincentAnderson please could you check and give me your feedback I fixed favorites functions and models to make unique entries on the FavoriteCourse table. Also, I tested and the tests passed with different users. I can favorite or unfavorite courses that I did not create.

Fix favorites

---

app/controllers/users/registrations_controller.rb

This PR handles the case where there's an error destroying the user

added some error handling

---

app/controllers/users/registrations_controller.rb
app/mailers/application_mailer.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/policies/user_policy.rb
app/views/layouts/mailer.html.erb
app/views/layouts/mailer.text.erb
app/views/user_mailer/new_registration.html.erb
app/views/user_mailer/new_registration.text.erb
app/views/user_mailer/welcome_email.html.erb
app/views/user_mailer/welcome_email.text.erb
config/routes.rb
spec/factories/users.rb
spec/mailers/previews/user_preview.rb
spec/mailers/user_spec.rb

@CharlesVincentAnderson this is the first part of the action mailer just for the welcome when we create a new user. I still need to work on the other methods to notify when we have changes on the account" Please do you mind checking this part and give me your feedback.

Action mailer welcome user

---

app/assets/stylesheets/pages.scss
app/views/pages/landing_page.html.erb

This PR centers the search bar on the landing page.

centered search bar on landing page

---

app/assets/stylesheets/layouts.scss
app/controllers/courses_controller.rb
app/views/layouts/application.html.erb

This PR makes minor changes to clean up some css

Trying alertajax

---

app/assets/stylesheets/courses.scss
app/views/courses/_form.html.erb
app/views/courses/course_lesson_form.html.erb
app/views/courses/show.html.erb
app/views/lessons/_form.html.erb

This PR adds styling to the course form

added styling for course form

---

app/assets/stylesheets/application.scss
app/models/concerns/search_item_search.rb
app/views/pages/search.html.erb
app/views/users/registrations/_user_card.html.erb
app/views/users/registrations/index.html.erb

This PR fixed some styling for user pagination and added pagination to search results

moved users pagination off of cards, added pagination to search

---

app/controllers/users/registrations_controller.rb
app/mailers/user_mailer.rb
app/views/user_mailer/update_email.text.erb
app/views/user_mailer/uptade_email.html.erb

@CharlesVincentAnderson I worked on the email right now is sending an email to confirm the account once the user updates the email". I still need to fix something, but I want to show you the first part of this request.

Send email when the user update email

---

app/controllers/users/registrations_controller.rb
app/mailers/user_mailer.rb
app/views/user_mailer/new_email.html.erb
app/views/user_mailer/new_email.txt.erb
app/views/user_mailer/update_email.text.erb
app/views/user_mailer/uptade_email.html.erb

@CharlesVincentAnderson please could you check this PR for the mail notification when the user updates his/her email and give me your feedback.

User update2

---

app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/controllers/users/registrations_controller.rb
app/mailers/user_mailer.rb
app/views/user_mailer/new_email.html.erb
app/views/user_mailer/new_email.txt.erb
app/views/user_mailer/update_email.text.erb
app/views/user_mailer/uptade_email.html.erb
db/seeds.rb

@CharlesVincentAnderson In this branch, I added two records in the seeds for favorites. Fix the warning for the missing params in favorites on the console after the last changes. I will add the parameter you requested and create some changes for the messages in another branch.

User update3

---

app/controllers/application_controller.rb
app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/controllers/users/registrations_controller.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/user_mailer/new_email.html.erb
app/views/user_mailer/new_email.txt.erb
app/views/user_mailer/update_email.text.erb
app/views/user_mailer/uptade_email.html.erb
db/migrate/20211105032157_add_previous_email_to_users.rb
db/schema.rb
db/seeds.rb

@CharlesVincentAnderson please can you check this version and give me your feedback. I added the column previous_email and changed the messages. The way it is working is that if I updated the email the new user's email will receive the confirmation email with the token and the old email will be working until the new user email will be confirmed.

User update4

---

app/assets/stylesheets/pages.scss
app/controllers/application_controller.rb
app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/controllers/users/registrations_controller.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/layouts/_search_landingpage.html.erb
app/views/pages/landing_page.html.erb
app/views/user_mailer/new_email.html.erb
app/views/user_mailer/new_email.txt.erb
app/views/user_mailer/update_email.text.erb
app/views/user_mailer/uptade_email.html.erb
db/migrate/20211105032157_add_previous_email_to_users.rb
db/schema.rb
db/seeds.rb

@CharlesVincentAnderson please can you check this branch and give me your feedback. In this branch, we center the search bar for the landing page.

User update6

---

app/assets/stylesheets/pages.scss
app/controllers/application_controller.rb
app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/controllers/users/registrations_controller.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/layouts/_search_landingpage.html.erb
app/views/pages/landing_page.html.erb
app/views/user_mailer/new_email.html.erb
app/views/user_mailer/new_email.txt.erb
app/views/user_mailer/update_email.text.erb
app/views/user_mailer/uptade_email.html.erb
db/migrate/20211105032157_add_previous_email_to_users.rb
db/schema.rb
db/seeds.rb

@CharlesVincentAnderson please can you check this PR and give me your feedback. I add the admin files to the seed.

Admins toseed

---

app/views/users/registrations/edit.html.erb

@CharlesVincentAnderson please could you check this PR and give me your feedback when you have a chance. It is just email validation for the edit view. If this is ok I will add the same method to validate in the create view.

Validation for email with JS

---

app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/users/registrations/edit.html.erb
app/views/users/registrations/new.html.erb

@CharlesVincentAnderson please can you check this PR and give me your feedback. In this PR we fix the last view to reset the password to match with the login and signup.

Format email4

---

app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/new.html.erb
app/views/users/registrations/edit.html.erb
app/views/users/registrations/new.html.erb

@CharlesVincentAnderson this is the last PR with email validation for the new user view. Please could you check it and give me your feedback.

Format email3

---

app/controllers/application_controller.rb
app/controllers/users/registrations_controller.rb
app/models/concerns/course_search.rb
app/models/user.rb
app/views/users/registrations/_user_card.html.erb
app/views/users/registrations/edit.html.erb
db/migrate/20211120045305_add_status_to_user.rb
db/schema.rb
db/seeds.rb

@CharlesVincentAnderson please can you check this branch and give me your feedback. We still have pending the policy feature to check the user's status.

User status feature

---

app/controllers/pages_controller.rb
app/models/concerns/search_item_search.rb

This PR filters my content so it is handled by ES

Filter my content

---

app/controllers/users/registrations_controller.rb
app/views/users/registrations/_user_card.html.erb
app/views/users/registrations/usercourses.html.erb
config/routes.rb
spec/factories/users.rb
spec/mailers/previews/user_preview.rb
spec/mailers/user_spec.rb
spec/models/user_spec.rb
spec/requests/sessions_spec.rb
spec/requests/users_spec.rb

@CharlesVincentAnderson please can you check it and give me your feedback. I added few tests for emails.

User rspecs2

---

app/controllers/users/registrations_controller.rb
app/views/users/registrations/_user_card.html.erb
app/views/users/registrations/usercourses.html.erb
config/routes.rb
spec/factories/users.rb
spec/requests/sessions_spec.rb
spec/requests/users_spec.rb

@CharlesVincentAnderson please can you check this PR and give me your feedback. You can see a few rspecs for users and a new view to show the courses associated with the user.

User rspecs

---

Dockerfile
app/views/layouts/application.html.erb
config/environments/production.rb

this PR resolves a conflict in the Dockerfile and removed a console.log

Trying moreuserspecs

---

app/controllers/users/registrations_controller.rb
app/views/pages/_course_card.html.erb
app/views/pages/_lesson_card.html.erb
app/views/users/registrations/_user_card.html.erb
app/views/users/registrations/edit.html.erb
app/views/users/registrations/new.html.erb
app/views/users/registrations/usercourses.html.erb
config/routes.rb
spec/factories/users.rb
spec/mailers/previews/user_preview.rb
spec/mailers/user_spec.rb
spec/models/user_spec.rb
spec/requests/sessions_spec.rb
spec/requests/users_spec.rb

@CharlesVincentAnderson please can you check this PR and give me your feedback. I decided to send the alert with a JS function when the user is not login.

Notsignedin

---

Dockerfile
app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/controllers/pages_controller.rb
app/models/concerns/search_item_search.rb
app/models/search_item.rb
app/views/layouts/application.html.erb
app/views/pages/_course_card.html.erb
app/views/pages/_lesson_card.html.erb
app/views/users/registrations/edit.html.erb
app/views/users/registrations/new.html.erb
db/migrate/20211130214440_add_user_last_name_to_search_item.rb
db/schema.rb
db/seeds.rb

@CharlesVincentAnderson Please can you check this branch and give me your feedback. I refactor the function checkUser as you requested.

Notsignedin2

---

Dockerfile
app/controllers/application_controller.rb
app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/controllers/pages_controller.rb
app/controllers/users/registrations_controller.rb
app/models/concerns/search_item_search.rb
app/models/search_item.rb
app/models/user.rb
app/views/users/registrations/edit.html.erb
db/migrate/20211209001518_add_user_status_to_search_item.rb
db/schema.rb
db/seeds.rb

This pr changes status to user_status on search_items and cleans up some code.

Trying index userstatus4

---

app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/controllers/users/registrations_controller.rb
app/models/search_item.rb
app/models/user.rb
db/migrate/20211209001518_add_user_status_to_search_item.rb
db/schema.rb
db/seeds.rb

@CharlesVincentAnderson please can you check this PR and give me your feedback. In this PR we update the user's last name and status in ElasticSearch records associated with the user that we updated.

Index user status

---

app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/views/courses/_form.html.erb
app/views/courses/course_lesson_form.html.erb
app/views/courses/show.html.erb
app/views/lessons/_form.html.erb
app/views/pages/_lesson_card.html.erb

This PR opens a lesson to an open lesson and scrolls down to it on page load.

Trying new routes fixing

---

app/assets/stylesheets/application.scss
app/controllers/users/registrations_controller.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/user_mailer/new_registration.html.erb
app/views/user_mailer/welcome_email.html.erb
spec/mailers/previews/user_preview.rb
spec/mailers/user_spec.rb
spec/models/user_spec.rb
spec/requests/courses_spec.rb
spec/requests/users_spec.rb

@CharlesVincentAnderson I fixed the link and the Teach for America" also I changed the width: 100; and height: auto; for the logo_end classes to adjust the image.

Fix mail confirmation3

---

app/controllers/users/registrations_controller.rb
app/mailers/user_mailer.rb
app/models/user.rb
spec/mailers/previews/user_preview.rb
spec/mailers/user_spec.rb
spec/models/user_spec.rb
spec/requests/courses_spec.rb
spec/requests/users_spec.rb

@CharlesVincentAnderson please can you check this branch. In this branch, I removed the extra mail confirmation.

Fix the mail confirmation

---

app/assets/stylesheets/courses.scss
app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/models/course.rb
app/models/flag.rb
app/models/lesson.rb
app/models/user.rb
app/policies/course_policy.rb
app/policies/lesson_policy.rb
app/views/courses/_form.html.erb
app/views/courses/show.html.erb
app/views/users/registrations/index.html.erb
config/routes.rb
db/migrate/20220216001853_create_flags.rb
db/schema.rb

@CharlesVincentAnderson in this branch I setup default status Approved for users and default view for index as index table instead of the cards

User view1

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/users.scss
app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/controllers/pages_controller.rb
app/mailers/user_mailer.rb
app/views/courses/_flag_modal.html.erb
app/views/courses/flag_modal.js.erb
app/views/layouts/_navigation.html.erb
app/views/layouts/_search_landingpage.html.erb
app/views/layouts/_search_user.html.erb
app/views/pages/search.html.erb
app/views/user_mailer/send_flag_notification.html.erb
app/views/user_mailer/send_flag_notification.html.erb.erb
app/views/user_mailer/send_flag_notification.text.erb
app/views/users/registrations/_index_table.html.erb
app/views/users/registrations/index.html.erb
spec/factories/flags.rb.rb
spec/mailers/previews/user_preview.rb

@CharlesVincentAnderson This is the last update for user_split to adjust the table. Do you mind checking it and giving me your feedback, please?

Split username2

---

app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/controllers/pages_controller.rb
app/mailers/user_mailer.rb
app/views/courses/_flag_modal.html.erb
app/views/courses/flag_modal.js.erb
app/views/layouts/_navigation.html.erb
app/views/layouts/_search_landingpage.html.erb
app/views/pages/search.html.erb
app/views/user_mailer/send_flag_notification.html.erb
app/views/user_mailer/send_flag_notification.html.erb.erb
app/views/user_mailer/send_flag_notification.text.erb
spec/factories/flags.rb.rb
spec/mailers/previews/user_preview.rb

@CharlesVincentAnderson Hi when you have. chance can you check this PR and give me your feedback please

Flag notification5

---

app/controllers/application_controller.rb
app/controllers/courses_controller.rb
app/controllers/documents_controller.rb
app/controllers/lessons_controller.rb
app/controllers/users/registrations_controller.rb
app/views/courses/show.html.erb

This PR blocks flagged content on the courses show page.  it also fixes a bug with the pundit policies

lesson unflag policy working and pundit error handling improved

---

app/views/lessons/_form.html.erb

This PR fixes the tag button on the lesson form and also removes PREVIEW from the table

fixed button and removed PREVIEW from lesson form

---

app/controllers/courses_controller.rb
app/models/course.rb

This PR adds more options for districts and subjects.

added more subjects and districts

---

app/views/pages/about.html.erb

This PR adds text to the about me page

added about me

---

app/models/course.rb
config/environments/production.rb

This PR adds districts to the course model.

added districts tocourse model

---

app/models/concerns/search_item_search.rb

This PR fixes a bug where the pagination wasn't changing pages.

fixed pagination bug

---

app/controllers/users/registrations_controller.rb
app/views/users/registrations/_index_card.html.erb
app/views/users/registrations/_index_table.html.erb

This PR adds pagination to the table view in the users index

fixed user pagination

---

app/controllers/courses_controller.rb
app/controllers/lessons_controller.rb
app/controllers/pages_controller.rb

Fixed redirect bugs for deleting courses and lessons

fixed delete redirect bugs

---

app/models/search_item.rb

This PR adds a callback in the search item model to reindex after a commit or delete

added callback to reindex on search item model

---

app/assets/stylesheets/pages.scss
app/views/pages/landing_page.html.erb

This PR adds 2 instructional videos to the landing page

Instructional videos

---

Dockerfile

This PR adds 'Run yarn add jquery' to Dockerfile.
Builds and runs locally

added Run yarn add jquery to Dockerfile
